# Display.
title: "Teaching Tech Together"
subtitle: "How to create and deliver lessons that work and build a teaching community around them"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/gvwilson/teachtogether.tech/"
email: "gvwilson@third-bit.com"
isbn: "978-0-9881137-0-1"
website: "http://teachtogether.tech/"
purchase: "http://www.lulu.com/commerce/index.php?fBuyContent=23123539"
paypal: "https://paypal.me/gvwilson/10CAD"

# Order for Table of Contents.
toc:
  lessons:
  - intro
  - models
  - memory
  - load
  - individual
  - process
  - pck
  - performance
  - classroom
  - motivation
  - online
  - exercises
  - community
  - marketing
  - partner
  - finale
  bib:
  - bib
  extras:
  - license
  - citation
  - joining
  - conduct
  - gloss
  - meetings
  - theory
  - template
  - events
  - teacheval
  - peereval
  - preassess
  - v3
# Tell Jekyll that "en" is a collection (whose files are found in "_en").  This
# is what allows us to loop over files in various inclusions.  We use "en" to
# indicate English, and can use other two-letter codes for other languages.
collections:
  en:
    output: true
    permalink: /:collection/:title/

# Specify the use of the "lesson" template for elements of the "en" collection.
defaults:
  - scope:
      path: ""
      type: en
    values:
      language: "en"
      layout: "lesson"

# Translations keyed by language.  This lookup table allows us to put the right
# titles on inclusion blocks in various languages.
translations:
  en:
    generated: "Last generated"
    questions: "Questions"
    keypoints: "Key Points"
    lulu: "Buy on Lulu"

# Standard Jekyll settings.
repository: <USERNAME>/<PROJECT>
highlighter: rouge
kramdown:
  auto_ids: false
plugins:
- "jekyll-redirect-from"
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- DESIGN.md
- LICENSE.md
- Makefile
- README.md
- bin
- etc
- misc
- node_modules
- requirements.txt
- src
- tex
