# Display.
title: "Teaching Tech Together"
subtitle: "How to create and deliver lessons that work and build a teaching community around them"
author: "Greg Wilson"
copyrightyear: "2018"
repo: "https://github.com/gvwilson/teachtogether.tech/"
email: "gvwilson@third-bit.com"
isbn: "978-0-9881137-0-1"
website: "http://teachtogether.tech/"
purchase: "http://www.lulu.com/commerce/index.php?fBuyContent=23123539"

# Theme color.
background: "#f0f0f0"

# Code highlighting.
highlighter: rouge

# Things to ignore
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- requirements.txt
- tex_en

# Collections: one for lessons and one for extras for each language suffix.
collections:
  chapters_en:
    output: true
  chapters_um:
    output: true

# Set the language for various collections.
defaults:
  - scope:
      path: ""
      type: chapters_en
    values:
      language: "en"
  - scope:
      path: ""
      type: chapters_um
    values:
      language: "um"

# Order for Table of Contents.
toc:
  lessons:
  - /intro/
  - /models/
  - /memory/
  - /load/
  - /individual/
  - /process/
  - /pck/
  - /performance/
  - /classroom/
  - /motivation/
  - /online/
  - /exercises/
  - /community/
  - /marketing/
  - /partner/
  - /final/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /bib/
  - /joining/
  - /gloss/
  - /meetings/
  - /theory/
  - /template/
  - /events/
  - /teacheval/
  - /peereval/
  - /preassess/
  - /v3/

# Translations by language.
translations:
  en:
    generated: "Last generated"
    objectives: "After reading this chapter, you will be able to..."
  um:
    generated: "Lastum generatum"
    objectives: "Sodales ut etiam sit amet nisl purus in..."
